version: "3"
services:
  rr-frontend:
    container_name: rr-node
    build: node/
    volumes:
      - ./node:/node
      - /node/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    # Ensure that postgres is running before starting up node
    depends_on:
      rr-db:
        condition: service_healthy
  rr-db:
    container_name: rr-postgres
    image: postgres
    restart: always
    shm_size: 128mb # set shared memory limit when using docker-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./postgres/scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 1s
      retries: 5
      timeout: 2s
